let paperData = {
  "papers": [
    {
      "title": "FLAME: Federated Learning Across Multi-device Environments",
      "venue": "ACM IMWUT (UbiComp) 2022",
      "authors": "**Hyunsung Cho**, Akhil Mathur, and Fahim Kawsar",
      "paper_link": null,
      "pdf": null,
      "award": null,
      "award2": null,
      "video": null,
      "website": null,
      "acm_dl": null,
    },
    {
      "title": "You Are Not Alone: How Trending Stress Topics Brought #Awareness and #Resonance on Campus",
      "venue": "ACM CSCW 2022",
      "authors": "Ryuhaerang Choi, Chanwoo Yoon, **Hyunsung Cho**, Hwajung Hong, Uichin Lee, and Sung-Ju Lee",
      "paper_link": null,
      "pdf": null,
      "award": null,
      "award2": null,
      "video": null,
      "website": null,
      "acm_dl": null,
    },
    {
      "title": "Prediction for Retrospection: Integrating Algorithmic Stress Prediction into Personal Informatics " +
          "Systems for College Students' Mental Health",
      "venue": "ACM CHI 2022",
      "authors": "Taewan Kim, Haesoo Kim, Ha Yeon Lee, Hwarang Goh, Shakhboz Abdigapporov, Mingon Jeong, " +
          "**Hyunsung Cho**, Kyungsik Han, Youngtae Noh, Sung-Ju Lee, and Hwajung Hong",
      "paper_link": "https://drive.google.com/file/d/15Mbmp5yQL4PuZuLA8on3dYVlt0MAHgzF/view",
      "pdf": "https://drive.google.com/file/d/15Mbmp5yQL4PuZuLA8on3dYVlt0MAHgzF/view",
      "award": null,
      "award2": null,
      "video": "https://www.youtube.com/watch?v=iATPtKkLFHo",
      "website": null,
      "acm_dl": null,
    },
    {
      "title": "Reflect, not Regret: Understanding Regretful Smartphone Use with App Feature-Level Analysis",
      "venue": "ACM CSCW 2021",
      "authors": "**Hyunsung Cho**, DaEun Choi, Donghwi Kim, Wan Ju Kang, Eun Kyoung Choe, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/10.1145/3479600",
      "pdf": "/pdf/CSCW21_Finesse.pdf",
      "slides": null,
      "award": "Best Paper Award",
      "award2": "Methods Recognition",
      "video": "https://www.youtube.com/watch?v=ZWva_OIv2xw",
      "website": null,
      "acm_dl": null,
    },
    {
      "title": "I Share, You Care: Private Status Sharing and Sender-Controlled Notifications in " +
          "Mobile Instant Messaging",
      "venue": "ACM CSCW 2020",
      "authors": "**Hyunsung Cho**, Jinyoung Oh, Juho Kim, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/abs/10.1145/3392839",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/CSCW20_MyButler.pdf",
      "slides": null,
      "award": null,
      "award2": null,
      "video": "https://www.youtube.com/watch?v=hUmjE5giPC0&feature=youtu.be",
      "website": "https://nmsl.kaist.ac.kr/projects/mybutler/",
    },
    {
      "title": "Knocker:  Vibroacoustic-based Object Recognition with Smartphones",
      "venue": "ACM IMWUT (UbiComp) 2019",
      "authors": "Taesik Gong, **Hyunsung Cho**, Bowon Lee, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/abs/10.1145/3351240",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/IMWUT19_Knocker.pdf",
      "slides": null,
      "award": null,
      "award2": null,
      "video": "https://www.youtube.com/watch?v=SyQn1vr_HeQ&feature=youtu.be",
      "website": "https://nmsl.kaist.ac.kr/projects/knocker/"
    },
    {
      "title": "Intelligent Positive Computing with Mobile,  Wearable,  and IoT Devices: Literature Review and Research Directions",
      "venue": "Ad Hoc Networks 2019",
      "authors": "Uichin Lee, Kyungsik Han, **Hyunsung Cho**, Kyong-Mee Chung, Hwajung Hong, Sung-Ju Lee, Youngtae Noh,Sooyoung Park,  and John M. Caroll.",
      "paper_link": "https://www.sciencedirect.com/science/article/pii/S157087051830619X",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/AdHoc19_Intelligent.pdf",
      "slides": null,
      "award": null,
      "award2": null,
      "video": null,
      "website": null,
    },


    // {
    //   "title": "",
    //   "venue": "",
    //   "authors": "",
    //   "paper_link": null,
    //   "slides": null,
    //   "award": null,
    //   "video": null,
    //   "website": null,
    // },
  ],
};

let posterData = {
  "posters": [
    {
      "title": "Facilitating Instant Interactions for Stressful Experiences Sharing and Peer Support",
      "venue": "ACM MobiSys 2022 Demos",
      "authors": "Ryuhaeraeng Choi, Chanwoo Yun, **Hyunsung Cho**, Hwajung Hong, Uichin Lee, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/10.1145/3498361.3538672",
      "pdf": null,
      "slides": null,
      "award": null,
      "video": null,
      "website": null
    },
    {
      "title": "Device or User: Rethinking Federated Learning in Personal-Scale Multi-Device Environments",
      "venue": "ACM SenSys 2021 Workshop on Challenges in Artificial Intelligence and Machine Learning for Internet of Things (AIChallengeIoT)",
      "authors": "**Hyunsung Cho**, Akhil Mathur, and Fahim Kawsar",
      "paper_link": "https://dl.acm.org/doi/abs/10.1145/3485730.3493449",
      "pdf": "https://dl.acm.org/doi/pdf/10.1145/3485730.3493449",
      "slides": null,
      "award": null,
      "video": null,
      "website": null
    },
    {
      "title": "I Share, You Care: Private Status Sharing and Sender-Controlled Notifications in " +
          "Mobile Instant Messaging",
      "venue": "ACM CSCW 2020 Demos",
      "authors": "**Hyunsung Cho**, Jinyoung Oh, Juho Kim, and Sung-Ju Lee",
      "pdf": "/pdf/CSCW20Demo_MyButler.pdf",
      "slides": null,
      "award": null,
      "video": null,
      "website": null
    },
    {
      "title": "Sender-Controlled Mobile Instant Message Notifications  Using  Activity Information",
      "venue": "ACM MobiSys 2019 Demos",
      "authors": "**Hyunsung Cho**, Jinyoung Oh, Juho Kim, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/10.1145/3307334.3329407",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/MobiSys19_MyButler.pdf",
      "slides": null,
      "award": null,
      "video": null,
      "website": null,
    },
    {
      "title": "Real-Time Object Identification with a Smartphone Knock",
      "venue": "ACM MobiSys 2019 Videos",
      "authors": "Taesik Gong, **Hyunsung Cho**, Bowon Lee, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/10.1145/3307334.3328593",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/MobiSys19_Real-Time.pdf",
      "slides": null,
      "award": "Best Video Award",
      "video": "https://www.youtube.com/watch?v=SyQn1vr_HeQ&feature=youtu.be",
      "website": null,
    },
    {
      "title": "Identifying Everyday Objects with a Smartphone Knock",
      "venue": "ACM CHI 2018 Late-Breaking Work",
      "authors": "Taesik Gong, **Hyunsung Cho**, Bowon Lee, and Sung-Ju Lee",
      "paper_link": "https://dl.acm.org/doi/10.1145/3170427.3188514",
      "pdf": "https://nmsl.kaist.ac.kr/pdf/CHIEA18_Identifying.pdf",
      "slides": null,
      "award": null,
      "video": null,
      "website": null,
    },
  ],
};


export { paperData, posterData };